###Register User
POST http://localhost:8764/auth/users
Content-Type: application/json

{
    "firstName":"vani",
    "lastName":"enaganti",
    "email":"vani@gmail.com",
    "password":"sree13",
    "role":"AUTHOR",
    "profileImageUrl":"image",
    "isUserActive":true
}

###Login User
POST http://localhost:8764/auth/login
Content-Type: application/json

{
    "email":"sreekar@gmail.com",
    "password":"sree12"
}

### User Logout
GET http://localhost:8764/auth/logout

###change password
PUT http://localhost:8764/auth/password
Content-Type:application/json

{
    "currentPassword":"sree12",
    "newPassword":"laasya"
}